phphost/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from views import *

urlpatterns = patterns('',
    url(r'^$',
        TemplateView.as_view(template_name="phphost/index.html"),
        name="phphost.dashboard.home", ),
    url(r'^dashboard/$',
        dashboard_home_view,
        name="phphost.dashboard.home", ),
    url(r'^dashboard/add/$',
        dashboard_hosting_add_view,
        name="phphost.dashboard.hosting.add", ),
    url(r'^dashboard/(?P<domain>[a-zA-Z0-9-.]+)/$',
        dashboard_hosting_view,
        name="phphost.dashboard.hosting", ),
    url(r'^dashboard/(?P<domain>[a-zA-Z0-9-.]+)/set-ftp-passwd/$',
        set_ftp_passwd_process,
        name="phphost.dashboard.hosting.set_ftp_passwd", ),
    url(r'^dashboard/(?P<domain>[a-zA-Z0-9-.]+)/set-mysql-passwd/$',
        set_mysql_passwd_process,
        name="phphost.dashboard.hosting.set_mysql_passwd", ),
    url(r'^dashboard/(?P<domain>[a-zA-Z0-9-.]+)/create-mysql-db/$',
        create_mysql_db_process,
        name="phphost.dashboard.hosting.create_mysql_db", ),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('phphost.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/profile/', RedirectView.as_view(url="/dashboard")),
    url(r'^register/', RedirectView.as_view(url="/accounts/register/")),
    url(r'^', include('login.urls')),
    url(r'^', include('password_reset.urls')),
    url(r'^', include('registration.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phphost/models.py
# coding=utf-8
# python
import urllib
import string
import random

# lib
import requests

# django
from django.db import models

# django contrib
from django.contrib.auth.models import User


def get_random_string(length, chars=string.ascii_lowercase+string.digits):
    return "".join([random.choice(chars) for i in xrange(length)])


class Server(models.Model):
    domain = models.CharField(max_length=64, unique=True)
    ip = models.IPAddressField()
    phm_origin = models.CharField(max_length=64)

    def __unicode__(self):
        return u'%s' % self.domain


class Hosting(models.Model):
    user = models.ForeignKey(User)
    server = models.ForeignKey(Server)

    domain = models.CharField(max_length=255, unique=True)
    created_at = models.DateField(auto_now_add=True)

    def get_ftp_server(self):
        return self.server.domain

    def get_ftp_user(self):
        return 'user%s' % self.id

    def get_php_my_admin_url(self):
        return 'http://pma.%s' % self.server.domain

    def get_mysql_server(self):
        return 'localhost'

    def get_mysql_user(self):
        return 'mysql%s' % self.id

    def _shm(self, path, attrs):
        res = requests.get('%s%s?%s' % (self.server.phm_origin, path, urllib.urlencode(attrs))).text
        print self.server.phm_origin, path, res
        status, status_code = res.split()
        return True if status == 'OK' else False, int(status_code)

    def shm_hosting_create(self):
        return self._shm('/hosting/create/', {
            'id': self.id,
            'server_name': self.domain,
            'server_aliases': 'www.%s' % self.domain,
        })

    def shm_mysql_user_create(self):
        return self._shm('/mysql/user/create/', {
            'user': self.get_mysql_user(),
            'passwd': get_random_string(10),
        })

    def shm_mysql_user_setpassword(self, passwd):
        return self._shm('/mysql/user/setpassword/', {
            'user': self.get_mysql_user(),
            'passwd': passwd,
        })

    def shm_mysql_db_create(self, suffix):
        return self._shm('/mysql/db/create/', {
            'name': '%s_%s' % (self.get_mysql_user(), suffix),
        })

    def shm_ftp_create(self):
        return self._shm('/ftp/create/', {
            'username': self.get_ftp_user(),
            'server_name': self.domain,
        })

    def shm_ftp_setpassword(self, passwd):
        return self._shm('/ftp/setpassword/', {
            'username': self.get_ftp_user(),
            'passwd': passwd,
        })

    def __unicode__(self):
        return u'%s' % self.domain

phphost/forms.py
# django
from django import forms

# local
from .models import Hosting


class HostingForm(forms.ModelForm):
    class Meta:
        model = Hosting
        fields = ["domain", ]

phphost/views.py
# django
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# django contrib
from django.contrib.auth.decorators import login_required

# local
from .models import Hosting, Server
from .forms import HostingForm
from .utils import sentry_log

def message_write(request, message):
    if 'messages' in request.session:
        request.session['messages'].append(message)
    else:
        request.session['messages'] = [message]
    request.session.save()


def message_get_all(request):
    messages = request.session.get('messages', [])
    request.session['messages'] = []
    return messages


@login_required
def dashboard_home_view(request):
    return render(request, 'phphost/dashboard/home.html')


@login_required
def dashboard_hosting_view(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: alert = request.GET["alert"]
    except KeyError: alert = ""
    return render(request, 'phphost/dashboard/hosting.html', {
        "hosting": hosting,
        "alert": alert,
        'messages': message_get_all(request),
    })


def dashboard_hosting_add_view(request):
    form = HostingForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.server = Server.objects.first()
        obj.save()
        s, rn = obj.shm_hosting_create()
        if s:
            message_write(request, ('success', 'Hosting byl vytvoren'))
        else:
            message_write(request, ('error', 'Nastala chyba #%s. Kontaktujte prosim podporu na <a href="mailto:support@phphost.cz">support@phphost.cz</a>' % rn))
            sentry_log('create apache host failed')
        s, rn = obj.shm_mysql_user_create()
        if s:
            message_write(request, ('success', 'MySQL uzivatel byl vytvoren'))
        else:
            message_write(request, ('error', 'Nastala chyba #%s. Kontaktujte prosim podporu na <a href="mailto:support@phphost.cz">support@phphost.cz</a>' % rn))
            sentry_log('create mysql user failed')
        return HttpResponseRedirect((reverse("phphost.dashboard.hosting", args=[obj.domain, ])))
    return render(request, 'phphost/dashboard/add_hosting.html', {
        "form": form,
    })


@login_required
def set_ftp_passwd_process(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: passwd = request.POST["passwd"]
    except KeyError: passwd = None
    if passwd:
        s, rn = hosting.shm_ftp_setpassword(passwd)
        if s:
            message_write(request, ('success', 'Heslo bylo zmeneno'))
        else:
            message_write(request, ('error', 'Nastala chyba #%s. Kontaktujte prosim podporu na <a href="mailto:support@phphost.cz">support@phphost.cz</a>' % rn))
            sentry_log('set ftp password failed')
    return HttpResponseRedirect(reverse("phphost.dashboard.hosting", args=[hosting.domain, ]))


@login_required
def set_mysql_passwd_process(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: passwd = request.POST["passwd"]
    except KeyError: passwd = None
    if passwd:
        s, rn = hosting.shm_mysql_user_setpassword(passwd)
        if s:
            message_write(request, ('success', 'Heslo bylo zmeneno'))
        else:
            message_write(request, ('error', 'Nastala chyba #%s. Kontaktujte prosim podporu na <a href="mailto:support@phphost.cz">support@phphost.cz</a>' % rn))
            sentry_log('set mysql password failed')
    return HttpResponseRedirect(reverse("phphost.dashboard.hosting", args=[hosting.domain, ]))


@login_required
def create_mysql_db_process(request, domain):
    hosting = get_object_or_404(Hosting, domain=domain)
    try: suffix = request.POST["suffix"]
    except KeyError: suffix = None
    if suffix and len(suffix) < 8:
        s, rn = hosting.shm_mysql_db_create(suffix)
        if s:
            message_write(request, ('success', 'Databaze byla vytvorena'))
        else:
            message_write(request, ('error', 'Nastala chyba #%s. Kontaktujte prosim podporu na <a href="mailto:support@phphost.cz">support@phphost.cz</a>' % rn))
            sentry_log('create mysql db failed')
    return HttpResponseRedirect(reverse("phphost.dashboard.hosting", args=[hosting.domain, ]))

phphost/templates/phphost/base.html
{% extends "base.html" %}
{%block body%}
    <!-- START PAGE -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">PHPhost.cz 2.0</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              <strong>{{request.user.username}}</strong> ({{ request.user.email }})
            </p>
            <ul class="nav">
              <li><a href="{% url "phphost.dashboard.home" %}">Home</a></li>
              <li><a href="{% url "phphost.dashboard.hosting.add" %}" >Přidat hosting</a></li>
              <li><a href="{% url 'password_reset' %}" target="_blank">Reset hesla</a></li>
              <li><a href="/logout/" class="navbar-link">Odhlásit se</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid" id="container">
      {% block base_content %}
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Domény</li>
              {% for obj in request.user.hosting_set.all %}
              <li><!--  class="active" --><a href="{% url "phphost.dashboard.hosting" obj.domain %}">{{obj.domain}}</a></li>
              {%endfor%}
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          {% block content %}

          {% endblock content %}
        </div><!--/span-->
      </div><!--/row-->
      {% endblock base_content %}
      <hr>

      <footer>
        <p>2012 - {% now "Y" %} &copy; PHPhost.cz</p>
      </footer>

    </div><!--/.fluid-container-->

    {%endblock body%}

phphost/templates/phphost/index.html
{% extends "base.html" %}

{%block body%}
<p style="text-align: center; padding-top: 50px; font-size: 40px;">
    <a href="/dashboard" >Administrace</a> | <a href="/registration" >Registrace</a> | 2012 - {% now "Y" %} &copy; PHPhost.cz
</p>
{%endblock body%}
{%block body2%}
<style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
<div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <!-- <li class="active"><a href="#">Home</a></li> -->
          <li><a href="/dashboard">Administrace</a></li>
          <!-- <li><a href="#">Contact</a></li> -->
        </ul>
        <h3 class="muted">PHPhost.cz</h3>
      </div>

      <hr>

      <!-- <div class="jumbotron">
        <h1>PHP hosting pro každého!</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <a class="btn btn-large btn-success" href="#">Sign up today</a>
      </div> -->
      <div class="row-fluid">
        <div class="span12">
            <div style="text-align:center;">
                <h1>PHP hosting pro každého!</h1>
                <p style="font-size:20px;">PHP5, MySQL5, Nette, WordPress, Joomla, Magento, phpMyAdmin, ...</p>
            </div>
        </div>
      </div>


      <hr>

      <div class="row-fluid">
{#        <div class="span12">#}
{#          <h2>Ceník</h2>#}
{#          <table class="table">#}
{#                <tr>#}
{#                    <th>Název</th>#}
{#                    <th>Cena</th>#}
{#                    <th>Prostor</th>#}
{#                    <th>Počet DB</th>#}
{#                    <th>Domény</th>#}
{#                    <th></th>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>Basic</td>#}
{#                    <td>399 Kč / rok</td>#}
{#                    <td>100 MB</td>#}
{#                    <td>neomezeně</td>#}
{#                    <td>neomezeně</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>Standard</td>#}
{#                    <td>499 Kč / rok</td>#}
{#                    <td>500 MB</td>#}
{#                    <td>neomezeně</td>#}
{#                    <td>neomezeně</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>Pro</td>#}
{#                    <td>599 Kč / rok</td>#}
{#                    <td>1 000 MB</td>#}
{#                    <td>neomezeně</td>#}
{#                    <td>neomezeně</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>Unlimit</td>#}
{#                    <td>999 Kč / rok</td>#}
{#                    <td>2 000 MB</td>#}
{#                    <td>neomezeně</td>#}
{#                    <td>neomezeně</td>#}
{#                </tr>#}
{#            </table>#}
{#        </div>#}
{#      </div>#}

      <hr>

      <div class="footer">
        <p>2012 - {% now "Y" %} &copy; PHPhost.cz</p>
      </div>

    </div> <!-- /container -->
{%endblock body2%}